import Head from 'next/head';
import type { FC } from 'react';
import { StyledPageWrapper } from './page-wrapper.styled';

interface IProps {
	className?: string;
	title?: string;
	description?: string;
}

const PageWrapper: FC<IProps> = ({
	children,
	title,
	description,
	className,
}) => (
	<StyledPageWrapper className={className}>
		<Head>
			<title>{title ? title : 'Generated by create next app'}</title>
			<meta
				name='description'
				content={`${
					description ? description : 'Generated by create next app'
				}`}
			/>
			<link rel='icon' href='/favicon.ico' />
		</Head>

		<main>{children}</main>
	</StyledPageWrapper>
);

export default PageWrapper;
